# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://slashpablo.github.io',
                'git_url': 'https://github.com/slashpablo/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.nbdevtest': { 'nbdev_hello_world.nbdevtest.foo': ('nbdevtest.html#foo', 'nbdev_hello_world/nbdevtest.py'),
                                             'nbdev_hello_world.nbdevtest.say_hello': ( 'nbdevtest.html#say_hello',
                                                                                        'nbdev_hello_world/nbdevtest.py')}}}
