"""Me testing out the capabilities of nbdev"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_nbdevtest.ipynb.

# %% auto #0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_nbdevtest.ipynb #fed49b8b
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_nbdevtest.ipynb #5b023483
def foo(): pass
